margin fix cuz like squashed = look shit
tovyblox/tovy pull request #11
Opened 2022-12-16 01:40 UTC by tozzleboy

2022-12-17 23:18 UTC, marinofranz requested changes
That's all that looks off to me, fix that, and I'll review again.

2022-12-17 23:18 UTC, marinofranz commented on pages/workspace/[id]/sessions/schedules.tsx
> +			{!!activeSessions.length && <div className="flex flex-col w-full gap-y-3">
Change gap margin to `2` instead of `3`.

2022-12-18 06:59 UTC, tozzleboy commented on pages/workspace/[id]/sessions/schedules.tsx
> +			{!!activeSessions.length && <div className="flex flex-col w-full gap-y-3">
I took the gap margin from the actual sessions page.

2022-12-18 19:14 UTC, marinofranz approved these changes
LGTM 👍

2022-12-18 19:14 UTC, merged